### ISSUE TITLE
Hackage revision to bump bounds?

### ISSUE THREAD

**Issue by luke-clifton** [bitc/hs-vault-tool#5]
Would be nice to use it with newer GHC.

**Comment by bitc** [comment]
Please send a pull request with all the changes needed, including a version bump, and then I will merge + upload the new version to Hackage.

**Comment by luke-clifton** [comment]
I believe everything is already in master (https://github.com/bitc/hs-vault-tool/commit/22b50c6b2130746899ceb35387a753dece895b2f)

Just no release has been made (I'd even be ok with a hackage revision instead of a release)

**Comment by bitc** [comment]
I've released version [0.1.0.1](https://hackage.haskell.org/package/vault-tool-0.1.0.1) to Hackage.
Closing
